#!/usr/bin/env python3
from __future__ import annotations

import json
import re
from pathlib import Path


def slugify(value: str, max_length: int = 96) -> str:
    collapsed = re.sub(r"[^A-Za-z0-9._-]+", "-", value.strip())
    collapsed = re.sub(r"-{2,}", "-", collapsed).strip("-._")
    collapsed = collapsed or "item"
    return collapsed[:max_length].rstrip("-._") or "item"


def normalize_timestamp(value: str) -> str:
    if "." in value:
        return value
    return f"{value}.000"


def segment(
    source_file: str,
    day: str,
    session_block: str,
    sequence: int,
    presenter: str,
    title: str,
    start: str,
    end: str,
    *,
    role: str = "presenter",
    notes: str = "",
    divergence: str = "",
) -> dict[str, str | int]:
    identifier = slugify(f"{day}-{session_block}-{sequence:02d}-{presenter}-{title}", max_length=128)
    return {
        "id": identifier,
        "source_file": source_file,
        "day": day,
        "session_block": session_block,
        "sequence": sequence,
        "presenter": presenter,
        "title": title,
        "role": role,
        "start": normalize_timestamp(start),
        "end": normalize_timestamp(end),
        "notes": notes,
        "divergence": divergence,
    }


def unmapped(source_file: str, reason: str, notes: str = "") -> dict[str, str]:
    return {
        "source_file": source_file,
        "reason": reason,
        "notes": notes,
    }


REPO_ROOT = Path(__file__).resolve().parents[1]
METADATA_DIR = REPO_ROOT / "data" / "unpromptedcon-org" / "metadata"

D1_S1_MORNING = r"data\unpromptedcon-org\vtt\2026-03-03T152703Z__86148219374__dr-at-secwest.net__Stage-1-Morning-Opening-Offensive-AI__audio_transcript__ecc892c1-6d9d-4107-96ef-5c900556cbbc.vtt"
D1_S1_LATE_MORNING = r"data\unpromptedcon-org\vtt\2026-03-03T184421Z__83826532500__dr-at-secwest.net__Stage-1-Late-Morning-Agents-in-Production-Vulnerability-Discovery__audio_transcript__bc035032-7a2c-4e21-835c-02530b9062c8.vtt"
D1_S1_EARLY_AFTERNOON = r"data\unpromptedcon-org\vtt\2026-03-03T204939Z__83377163171__dr-at-secwest.net__Stage-1-Early-Afternoon-Attack-Surface-Browser-Exploitation-AI-Notetakers__audio_transcript__6e9e8de3-483f-4e65-8370-3098c4f706c4.vtt"
D1_S1_LATE_AFTERNOON = r"data\unpromptedcon-org\vtt\2026-03-03T224142Z__84095825429__dr-at-secwest.net__Stage-1-Late-Afternoon-Hardware-Hacking-Post-Training-LLM-Threats__audio_transcript__0bab1277-dfd8-4d45-9f47-80c8658c097a.vtt"

D1_S2_MORNING = r"data\unpromptedcon-org\vtt\2026-03-03T152817Z__86896161688__dr-at-secwest.net__Stage-2-Morning-AI-Governance__audio_transcript__b43fd2f8-1b2d-4ccb-8e06-53a16996f74d.vtt"
D1_S2_LATE_MORNING = r"data\unpromptedcon-org\vtt\2026-03-03T184601Z__88306059555__dr-at-secwest.net__Stage-2-Late-Morning-Military-AI-DFIR-GenAI-Detection__audio_transcript__7017aefa-57a1-44e0-85c7-cfe43f11d48b.vtt"
D1_S2_EARLY_AFTERNOON = r"data\unpromptedcon-org\vtt\2026-03-03T202444Z__88453714013__dr-at-secwest.net__Stage-2-Early-Afternoon-Confidential-AI-Synthetic-Vulns__audio_transcript__ed382938-d51d-4135-a3aa-e1eaf86d2e66.vtt"
D1_S2_LATE_AFTERNOON = r"data\unpromptedcon-org\vtt\2026-03-03T225057Z__84989988851__dr-at-secwest.net__Stage-2-Late-Afternoon-Interpretability-Risk-Frameworks-Physical-AI__audio_transcript__d649ccc8-564b-413d-82e6-d1b502959185.vtt"

D2_S1_MORNING = r"data\unpromptedcon-org\vtt\2026-03-04T154728Z__85233961465__dr-at-secwest.net__Stage-1-Morning-Opening-Offensive-AI-macOS-Research__audio_transcript__223ba898-07e4-48cd-9797-7a87b1d0cbb3.vtt"
D2_S1_LATE_MORNING = r"data\unpromptedcon-org\vtt\2026-03-04T185407Z__87222654977__dr-at-secwest.net__Stage-1-Late-Morning-Bug-Hunting-Red-Teaming-Secure-Agents__audio_transcript__06821b5f-9ea8-4b4b-ab90-775c13e48413.vtt"
D2_S1_EARLY_AFTERNOON = r"data\unpromptedcon-org\vtt\2026-03-04T211446Z__84833379255__dr-at-secwest.net__Stage-1-Early-Afternoon-Securing-GenAI-at-Scale__audio_transcript__8056cf4c-125b-4f77-95bd-4d25af4349a4.vtt"
D2_S1_LATE_AFTERNOON = r"data\unpromptedcon-org\vtt\2026-03-04T225103Z__86986364381__dr-at-secwest.net__Stage-1-Late-Afternoon-Threat-Intel-Deception-Promptware__audio_transcript__14e9ad12-0df1-4dde-bfda-9b09261f53f3.vtt"

D2_S2_MORNING = r"data\unpromptedcon-org\vtt\2026-03-04T154833Z__89954966102__dr-at-secwest.net__Stage-2-Morning-Agent-Recon-IDE-Attacks-Capability-Auth__audio_transcript__edd74662-a38d-423d-8fdf-09a855eaff50.vtt"
D2_S2_LATE_MORNING = r"data\unpromptedcon-org\vtt\2026-03-04T185503Z__89375426759__dr-at-secwest.net__Stage-2-Late-Morning-Secure-Coding-Prompt-Injection-Policy-Enforcement__audio_transcript__1974b177-b9d2-4ab2-9c85-24f4835ae7bc.vtt"
D2_S2_EARLY_AFTERNOON = r"data\unpromptedcon-org\vtt\2026-03-04T211531Z__87174872040__dr-at-secwest.net__Stage-2-Early-Afternoon-SOC-Automation-AI-Guarantees-Threat-Hunting__audio_transcript__2ed64979-9011-443c-bec1-8a9dc2da9ea7.vtt"
D2_S2_LATE_AFTERNOON = r"data\unpromptedcon-org\vtt\2026-03-04T224923Z__82468242121__dr-at-secwest.net__Stage-2-Late-Afternoon-Agentic-SOC-AI-Incidents-Vuln-Discovery__audio_transcript__eecef481-bd16-4ef1-a5a2-9bacf436d57e.vtt"

KEN_LUNCH = r"data\unpromptedcon-org\vtt\2026-03-03T202810Z__88690394827__dr-at-secwest.net__Lunch-Chat-Ken-Huang-Fellow-Cloud-Security-Alliance-Agentic-AI__audio_transcript__571a435b-b38d-4afb-995d-236b8b506b3b.vtt"
RICH_BOF = r"data\unpromptedcon-org\vtt\2026-03-04T205738Z__88923818522__dr-at-secwest.net__Birds-of-a-Feather-Agentic-Identity-Architecture-Chris-Cochran__audio_transcript__368ad121-2680-42f1-afac-eda5e0f934a9.vtt"

SEGMENTS = [
    segment(
        D1_S1_MORNING,
        "2026-03-03",
        "Stage 1 Morning Opening Offensive AI",
        1,
        "Gadi Evron",
        "Opening Words",
        "00:00:01",
        "00:11:14",
        role="host",
        notes="Conference welcome and framing for day one.",
    ),
    segment(
        D1_S1_MORNING,
        "2026-03-03",
        "Stage 1 Morning Opening Offensive AI",
        2,
        "Heather Adkins and Four Flynn",
        "Evaluating Threats & Automating Defense: How Google is Advancing Code Security",
        "00:15:37",
        "00:35:17",
        notes="Google / DeepMind talk.",
    ),
    segment(
        D1_S1_MORNING,
        "2026-03-03",
        "Stage 1 Morning Opening Offensive AI",
        3,
        "Joshua Saxe",
        "The Hard Part Isn't Building the Agent: On Measuring Agent Effectiveness",
        "00:44:09",
        "01:07:17",
    ),
    segment(
        D1_S1_MORNING,
        "2026-03-03",
        "Stage 1 Morning Opening Offensive AI",
        4,
        "Shruti Datta Gupta and Chandrani",
        "Security Guidance as a Service: Building an AI-Native Blueprint for Defensive Security",
        "01:07:53",
        "01:30:16",
        notes="Adobe security guidance talk; second speaker name is incomplete in ASR.",
    ),
    segment(
        D1_S1_LATE_MORNING,
        "2026-03-03",
        "Stage 1 Late Morning Agents in Production Vulnerability Discovery",
        1,
        "Jeffrey Zhang and Sid",
        "Guardrails beyond Vibes: Shipping Security Agents in Production",
        "00:03:10",
        "00:24:23",
        divergence="This talk appears in the late-morning recording even though it was listed in the morning block.",
    ),
    segment(
        D1_S1_LATE_MORNING,
        "2026-03-03",
        "Stage 1 Late Morning Agents in Production Vulnerability Discovery",
        2,
        "Paul McMillan and Ryan Lopopolo",
        "Code Is Free: Securing Software in the Agentic Future",
        "00:27:13",
        "00:52:00",
    ),
    segment(
        D1_S1_LATE_MORNING,
        "2026-03-03",
        "Stage 1 Late Morning Agents in Production Vulnerability Discovery",
        3,
        "Brendan Dolan-Gavitt and Vincent Olson",
        "AI Agents for Exploiting Auth-by-One Errors",
        "00:52:39",
        "01:10:56",
    ),
    segment(
        D1_S1_LATE_MORNING,
        "2026-03-03",
        "Stage 1 Late Morning Agents in Production Vulnerability Discovery",
        4,
        "Waris Gill and Natalie Isak",
        "Developing & Deploying AI Fingerprints for Advanced Threat Detection",
        "01:12:16",
        "01:31:01",
        notes="BinaryShield talk; Matthew Dressman is not clearly audible in the transcript.",
    ),
    segment(
        D1_S1_EARLY_AFTERNOON,
        "2026-03-03",
        "Stage 1 Early Afternoon Attack Surface Browser Exploitation AI Notetakers",
        1,
        "Sean Park",
        "When Passports Execute: Exploiting AI-Driven KYC Pipelines",
        "00:00:00",
        "00:13:13",
        notes="The file starts mid-talk, so the opening of Sean's presentation is clipped.",
        divergence="Sean Park's talk begins in this file rather than the prior late-morning file.",
    ),
    segment(
        D1_S1_EARLY_AFTERNOON,
        "2026-03-03",
        "Stage 1 Early Afternoon Attack Surface Browser Exploitation AI Notetakers",
        2,
        "Peter Girnus",
        "FENRIR: AI Hunting for AI Zero-Days at Scale",
        "00:13:50",
        "00:34:46",
    ),
    segment(
        D1_S1_EARLY_AFTERNOON,
        "2026-03-03",
        "Stage 1 Early Afternoon Attack Surface Browser Exploitation AI Notetakers",
        3,
        "Joe Sullivan",
        "AI Notetakers: The Most Important Person in the Room",
        "00:36:05",
        "00:55:31",
    ),
    segment(
        D1_S1_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 1 Late Afternoon Hardware Hacking Post-Training LLM Threats",
        1,
        "Adam Laurie",
        "AI go Beep Boop!",
        "00:01:00",
        "00:27:32",
        divergence="Adam Laurie's talk appears in the late-afternoon file rather than the prior early-afternoon file.",
    ),
    segment(
        D1_S1_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 1 Late Afternoon Hardware Hacking Post-Training LLM Threats",
        2,
        "Gadi Evron",
        "Post-Adam host remarks and Rami McCarthy intro",
        "00:27:32",
        "00:30:32",
        role="host",
        notes="Separated because the user asked for Gadi's host comments to be split out.",
    ),
    segment(
        D1_S1_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 1 Late Afternoon Hardware Hacking Post-Training LLM Threats",
        3,
        "Rami McCarthy",
        "Zeal of the Convert: Taming Shai-Hulud with AI",
        "00:30:35",
        "00:53:56",
    ),
    segment(
        D1_S1_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 1 Late Afternoon Hardware Hacking Post-Training LLM Threats",
        4,
        "Daniel Miessler",
        "Anatomy of an Agentic Personal AI Infrastructure",
        "00:54:34",
        "01:22:02",
        divergence="Daniel Miessler's talk appears here even though it was missing from the public slide deck list.",
    ),
    segment(
        D1_S1_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 1 Late Afternoon Hardware Hacking Post-Training LLM Threats",
        5,
        "Nicholas Carlini",
        "Black-hat LLMs",
        "01:22:36",
        "01:47:52",
    ),
    segment(
        D1_S1_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 1 Late Afternoon Hardware Hacking Post-Training LLM Threats",
        6,
        "Piotr Ryciak",
        "Vibe Check: Security Failures in AI-Assisted IDEs",
        "01:48:50",
        "02:14:41",
    ),
    segment(
        D1_S2_MORNING,
        "2026-03-03",
        "Stage 2 Morning AI Governance",
        1,
        "Billy Norwood",
        "Establishing AI Governance Without Stifling Innovation",
        "00:04:01",
        "00:29:21",
    ),
    segment(
        D1_S2_MORNING,
        "2026-03-03",
        "Stage 2 Morning AI Governance",
        2,
        "Ragini Ramalingam",
        "Enterprise AI Governance at Snowflake: Balancing Innovation and Risk",
        "00:30:08",
        "00:55:29",
    ),
    segment(
        D1_S2_LATE_MORNING,
        "2026-03-03",
        "Stage 2 Late Morning Military AI DFIR GenAI Detection",
        1,
        "Chase Hasbrouck",
        "Three Phases of AI Adoption: From GPU Lottery to Enterprise Agreements",
        "00:00:44",
        "00:23:45",
        divergence="Chase Hasbrouck's talk spills over from the Stage 2 morning recording into this late-morning file.",
    ),
    segment(
        D1_S2_LATE_MORNING,
        "2026-03-03",
        "Stage 2 Late Morning Military AI DFIR GenAI Detection",
        2,
        "Rob T. Lee",
        "SIFT - FIND EVIL!! I Gave Claude Code R00t on the DFIR SIFT Workstation",
        "00:24:47",
        "00:48:22",
    ),
    segment(
        D1_S2_LATE_MORNING,
        "2026-03-03",
        "Stage 2 Late Morning Military AI DFIR GenAI Detection",
        3,
        "Mika Ayenson",
        "GenAI Endpoint Observability",
        "00:48:48",
        "01:12:17",
    ),
    segment(
        D1_S2_LATE_MORNING,
        "2026-03-03",
        "Stage 2 Late Morning Military AI DFIR GenAI Detection",
        4,
        "Mohamed Nabeel",
        "Detecting GenAI Threats at Scale with YARA-Like Semantic Rules",
        "01:12:33",
        "01:31:09",
    ),
    segment(
        D1_S2_EARLY_AFTERNOON,
        "2026-03-03",
        "Stage 2 Early Afternoon Confidential AI Synthetic Vulns",
        1,
        "Raghu Yeluri",
        "The Advent of Confidential AI",
        "00:00:52",
        "00:25:21",
    ),
    segment(
        D1_S2_EARLY_AFTERNOON,
        "2026-03-03",
        "Stage 2 Early Afternoon Confidential AI Synthetic Vulns",
        2,
        "Aaron Grattafiori and Skylar",
        "Tenderizing the Target: Soaking Code in Synthetic Vulnerabilities",
        "00:29:33",
        "00:55:28",
        notes="The transcript clearly shows Aaron handing the Project Marinade talk to Skylar mid-presentation.",
    ),
    segment(
        D1_S2_EARLY_AFTERNOON,
        "2026-03-03",
        "Stage 2 Early Afternoon Confidential AI Synthetic Vulns",
        3,
        "Matt Maisel",
        "Hooking Coding Agents with the Cedar Policy Language",
        "00:59:20",
        "01:16:23",
    ),
    segment(
        D1_S2_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 2 Late Afternoon Interpretability Risk Frameworks Physical AI",
        1,
        "Carl Hurd",
        "Glass-Box Security: Operationalizing Mechanistic Interpretability for Defending AI Agents",
        "00:00:28",
        "00:29:02",
    ),
    segment(
        D1_S2_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 2 Late Afternoon Interpretability Risk Frameworks Physical AI",
        2,
        "Maxim Kovalsky",
        "The AI Security Larsen Effect: How to Stop the Feedback Loop",
        "00:29:03",
        "00:51:21",
        notes="Matched by order, self-intro as Max, and topic content.",
    ),
    segment(
        D1_S2_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 2 Late Afternoon Interpretability Risk Frameworks Physical AI",
        3,
        "Padma Apparao",
        "Kinetic Risk: Securing and Governing Physical AI in the Wild",
        "00:51:34",
        "01:19:17",
    ),
    segment(
        D1_S2_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 2 Late Afternoon Interpretability Risk Frameworks Physical AI",
        4,
        "Aaron Brown",
        "Trajectory-Aware Post-Training for Security Agents",
        "01:19:17",
        "01:45:19",
    ),
    segment(
        D1_S2_LATE_AFTERNOON,
        "2026-03-03",
        "Stage 2 Late Afternoon Interpretability Risk Frameworks Physical AI",
        5,
        "Adam Krivka and Ondrej Vlcek",
        "AI Found 12 Zero-Days In OpenSSL: What Does It Mean For The Industry?",
        "01:45:45",
        "02:10:15",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        1,
        "Kyle Rosenthal",
        "Day 2 kickoff and mayor introduction",
        "00:01:19",
        "00:02:09",
        role="host",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        2,
        "Mayor Daniel Lurie",
        "Welcome remarks",
        "00:02:17",
        "00:07:35",
        notes="Guest welcome to the conference.",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        3,
        "Gadi Evron",
        "Opening Words",
        "00:08:30",
        "00:14:35",
        role="host",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        4,
        "Rob Lee",
        "Unscheduled mini-demo: AI-native DFIR and SIFT workstation",
        "00:14:46",
        "00:18:18",
        divergence="This unscheduled demo appears before the scheduled Stage 1 talks begin.",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        5,
        "Glenn Thorpe",
        "Unscheduled mini-demo: vibe-coded conference agenda app",
        "00:19:36",
        "00:24:40",
        divergence="This unscheduled demo appears before the scheduled Stage 1 talks begin.",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        6,
        "Unidentified speaker",
        "Community remarks on communicating AI and security change",
        "00:25:15",
        "00:29:18",
        notes="The speaker name is too garbled in the transcript to identify confidently.",
        divergence="This unscheduled community segment appears before the scheduled Stage 1 talks begin.",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        7,
        "Gadi Evron",
        "Inserted Zenity stand-in presentation",
        "00:30:41",
        "00:37:28",
        notes="Gadi explicitly says he is presenting Zenity's slides because the speaker could not get out of Israel.",
        divergence="A Zenity stand-in talk was inserted here; the official public title is uncertain from the transcript content.",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        8,
        "Gadi Evron",
        "Bridge and Dan Guido introduction",
        "00:37:34",
        "00:39:50",
        role="host",
        notes="Separated because the user requested Gadi's host remarks be split out.",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        9,
        "Dan Guido",
        "200 Bugs/Week/Engineer: How We Rebuilt Trail of Bits Around AI",
        "00:39:50",
        "01:07:30",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        10,
        "Sergej Epp",
        "8 Minutes to Admin: Welcome to VibeHacking",
        "01:07:38",
        "01:25:08",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        11,
        "Gadi Evron",
        "Olivia Gallucci introduction",
        "01:25:08",
        "01:26:32",
        role="host",
    ),
    segment(
        D2_S1_MORNING,
        "2026-03-04",
        "Stage 1 Morning Opening Offensive AI macOS Research",
        12,
        "Olivia Gallucci",
        "macOS Vulnerability Research with AI Agents",
        "01:26:32",
        "01:47:15",
    ),
    segment(
        D2_S1_LATE_MORNING,
        "2026-03-04",
        "Stage 1 Late Morning Bug Hunting Red Teaming Secure Agents",
        1,
        "Georgi G",
        "Prompt2Pwn: LLMs Winning at Pwn2Own",
        "00:01:41",
        "00:26:32",
    ),
    segment(
        D2_S1_LATE_MORNING,
        "2026-03-04",
        "Stage 1 Late Morning Bug Hunting Red Teaming Secure Agents",
        2,
        "Andrew Bullen",
        "Breaking the Lethal Trifecta (Without Ruining Your Agents)",
        "00:27:49",
        "00:47:01",
    ),
    segment(
        D2_S1_LATE_MORNING,
        "2026-03-04",
        "Stage 1 Late Morning Bug Hunting Red Teaming Secure Agents",
        3,
        "Brooks McMillin",
        "Building Secure Agentic Systems: Lessons from Daily-Driver Agents",
        "00:47:12",
        "01:09:29",
    ),
    segment(
        D2_S1_LATE_MORNING,
        "2026-03-04",
        "Stage 1 Late Morning Bug Hunting Red Teaming Secure Agents",
        4,
        "Mudita Khurana",
        "Rethinking Security Agent Evaluation",
        "01:09:50",
        "01:19:50",
        divergence="Mudita Khurana's talk appears here at the end of late morning rather than in the early-afternoon file.",
    ),
    segment(
        D2_S1_EARLY_AFTERNOON,
        "2026-03-04",
        "Stage 1 Early Afternoon Securing GenAI at Scale",
        1,
        "Nicolas Lidzborski",
        "Securing Workspace GenAI at Google Speed: Surviving the Perfect Storm",
        "00:02:29",
        "00:28:03",
    ),
    segment(
        D2_S1_EARLY_AFTERNOON,
        "2026-03-04",
        "Stage 1 Early Afternoon Securing GenAI at Scale",
        2,
        "Josiah Pitakale",
        "Operation Pale Fire: Red-Teaming Our Own AI Agent",
        "00:29:01",
        "00:50:28",
        notes="The transcript identifies Josiah as the speaker while crediting Wes Ring and the Block team.",
    ),
    segment(
        D2_S1_EARLY_AFTERNOON,
        "2026-03-04",
        "Stage 1 Early Afternoon Securing GenAI at Scale",
        3,
        "Kyle Polley",
        "Training BrowseSafe: Prompt Injection in Browser Agents",
        "00:50:44",
        "01:20:23",
        divergence="Kyle Polley's talk appears here instead of the later afternoon block listed publicly.",
    ),
    segment(
        D2_S1_LATE_AFTERNOON,
        "2026-03-04",
        "Stage 1 Late Afternoon Threat Intel Deception Promptware",
        1,
        "Arthi Nagarajan",
        "Exploring the AI Automation Boundary for Threat Hunting",
        "00:01:32",
        "00:24:18",
    ),
    segment(
        D2_S1_LATE_AFTERNOON,
        "2026-03-04",
        "Stage 1 Late Afternoon Threat Intel Deception Promptware",
        2,
        "boB Rudis and Glenn Thorpe",
        "Detection & Deception Engineering in the Matrix",
        "00:24:32",
        "00:49:53",
    ),
    segment(
        D2_S1_LATE_AFTERNOON,
        "2026-03-04",
        "Stage 1 Late Afternoon Threat Intel Deception Promptware",
        3,
        "Community speakers",
        "Open flash talks and conference closing",
        "00:53:14",
        "01:27:21",
        role="discussion",
        notes="Open-mic closing block with multiple brief speakers including Chris Blanco and others.",
        divergence="The scheduled Chris Cochran lightning talk is not clearly present here; instead the file ends with open flash talks.",
    ),
    segment(
        D2_S2_MORNING,
        "2026-03-04",
        "Stage 2 Morning Agent Recon IDE Attacks Capability Auth",
        1,
        "Rowie",
        "Unscheduled agent reconnaissance talk",
        "00:00:24.895",
        "00:20:53.035",
        notes="The speaker self-identifies as Rowie and describes a 20-minute session about agent reconnaissance.",
        divergence="This talk is not part of the published Stage 2 morning agenda.",
    ),
    segment(
        D2_S2_MORNING,
        "2026-03-04",
        "Stage 2 Morning Agent Recon IDE Attacks Capability Auth",
        2,
        "Johann Rehberger",
        "Your Agent Works for Me Now",
        "00:20:53.035",
        "00:46:31.465",
        divergence="Johann Rehberger's talk appears in the morning file instead of the later block suggested by the public agenda.",
    ),
    segment(
        D2_S2_MORNING,
        "2026-03-04",
        "Stage 2 Morning Agent Recon IDE Attacks Capability Auth",
        3,
        "Gadi Evron",
        "Lightning-talk challenge before Niki Aimable Niyikiza",
        "00:46:31.465",
        "00:47:12.095",
        role="host",
    ),
    segment(
        D2_S2_MORNING,
        "2026-03-04",
        "Stage 2 Morning Agent Recon IDE Attacks Capability Auth",
        4,
        "Niki Aimable Niyikiza",
        "Capability-Based Authorization for AI Agents",
        "00:47:12.095",
        "01:15:49.545",
    ),
    segment(
        D2_S2_MORNING,
        "2026-03-04",
        "Stage 2 Morning Agent Recon IDE Attacks Capability Auth",
        5,
        "Gadi Evron",
        "Host intro for surprise lightning talk",
        "01:15:49.545",
        "01:16:24.255",
        role="host",
    ),
    segment(
        D2_S2_MORNING,
        "2026-03-04",
        "Stage 2 Morning Agent Recon IDE Attacks Capability Auth",
        6,
        "Jackson",
        "Are You Thinking What I'm Thinking?",
        "01:16:24.255",
        "01:21:49.905",
        divergence="This lightning talk was explicitly described as a surprise addition that was not on the schedule.",
    ),
    segment(
        D2_S2_MORNING,
        "2026-03-04",
        "Stage 2 Morning Agent Recon IDE Attacks Capability Auth",
        7,
        "Xenia Mountrouidou",
        "Traditional ML vs LLMs: Who Can Classify Better?",
        "01:21:49.905",
        "01:29:19.785",
        divergence="Xenia's talk appears in the morning file instead of the final late-afternoon block listed publicly.",
    ),
    segment(
        D2_S2_LATE_MORNING,
        "2026-03-04",
        "Stage 2 Late Morning Secure Coding Prompt Injection Policy Enforcement",
        1,
        "Srajan Gupta",
        "Injecting Security Context During Vibe Coding",
        "00:01:33.891",
        "00:25:35.731",
    ),
    segment(
        D2_S2_LATE_MORNING,
        "2026-03-04",
        "Stage 2 Late Morning Secure Coding Prompt Injection Policy Enforcement",
        2,
        "Justice Cassell and Scott Behrens",
        "Source to Sink: LLM First-Party Vuln Discovery",
        "00:25:35.731",
        "00:53:19.141",
        notes="Justice Cassell is the clearly audible co-speaker alongside Scott Behrens.",
    ),
    segment(
        D2_S2_LATE_MORNING,
        "2026-03-04",
        "Stage 2 Late Morning Secure Coding Prompt Injection Policy Enforcement",
        3,
        "Joey Melo",
        "The Parseltongue Protocol: 100+ Textual Obfuscation Methods",
        "00:53:19.141",
        "01:12:32.501",
    ),
    segment(
        D2_S2_LATE_MORNING,
        "2026-03-04",
        "Stage 2 Late Morning Secure Coding Prompt Injection Policy Enforcement",
        4,
        "Jenny Guanni Qu",
        "Why Most ML Vulnerability Detection Fails",
        "01:12:32.501",
        "01:25:19.671",
        divergence="Jenny's talk appears here rather than in the final late-afternoon block.",
    ),
    segment(
        D2_S2_EARLY_AFTERNOON,
        "2026-03-04",
        "Stage 2 Early Afternoon SOC Automation AI Guarantees Threat Hunting",
        1,
        "Millie and Matt Rittinghouse",
        "1.8M Prompts, 30 Alerts: Hunting Abuse in Agent Ecosystem",
        "00:00:01.771",
        "00:21:47.701",
        divergence="This talk appears at the start of the early-afternoon file rather than in the public late-morning slot.",
    ),
    segment(
        D2_S2_EARLY_AFTERNOON,
        "2026-03-04",
        "Stage 2 Early Afternoon SOC Automation AI Guarantees Threat Hunting",
        2,
        "Gadi Evron",
        "Transition to Ilia Shumailov",
        "00:21:47.701",
        "00:24:14.601",
        role="host",
    ),
    segment(
        D2_S2_EARLY_AFTERNOON,
        "2026-03-04",
        "Stage 2 Early Afternoon SOC Automation AI Guarantees Threat Hunting",
        3,
        "Ilia Shumailov",
        "AI Security with Guarantees",
        "00:24:14.601",
        "00:49:42.451",
    ),
    segment(
        D2_S2_EARLY_AFTERNOON,
        "2026-03-04",
        "Stage 2 Early Afternoon SOC Automation AI Guarantees Threat Hunting",
        4,
        "Dongdong Sun",
        "From OSINT Chaos to Knowledge Graph",
        "00:49:42.451",
        "01:16:31.641",
    ),
    segment(
        D2_S2_LATE_AFTERNOON,
        "2026-03-04",
        "Stage 2 Late Afternoon Agentic SOC AI Incidents Vuln Discovery",
        1,
        "Peter Smith and RK",
        "Beyond the Chatbot: Delivering an Agentic SOC",
        "00:00:11.266",
        "00:26:00.306",
    ),
    segment(
        D2_S2_LATE_AFTERNOON,
        "2026-03-04",
        "Stage 2 Late Afternoon Agentic SOC AI Incidents Vuln Discovery",
        2,
        "Akash Mukherjee",
        "Are Your LLM's Safety Mechanisms Intact?",
        "00:26:14.996",
        "00:50:59.166",
    ),
    segment(
        D2_S2_LATE_AFTERNOON,
        "2026-03-04",
        "Stage 2 Late Afternoon Agentic SOC AI Incidents Vuln Discovery",
        3,
        "Gadi Evron",
        "Host intro for lightning talk",
        "00:50:59.166",
        "00:51:16.466",
        role="host",
        notes="Speaker attribution is inferred from the transcript analysis.",
    ),
    segment(
        D2_S2_LATE_AFTERNOON,
        "2026-03-04",
        "Stage 2 Late Afternoon Agentic SOC AI Incidents Vuln Discovery",
        4,
        "Yerna and Gosha",
        "Jean-Claude Van CTF",
        "00:51:16.466",
        "01:01:24.176",
        divergence="This extra lightning talk appears instead of one of the published late-afternoon talks.",
    ),
    segment(
        D2_S2_LATE_AFTERNOON,
        "2026-03-04",
        "Stage 2 Late Afternoon Agentic SOC AI Incidents Vuln Discovery",
        5,
        "Gadi Evron",
        "Open-mic filler before final lightning talk",
        "01:01:24.176",
        "01:03:15.556",
        role="host",
        notes="Speaker attribution is inferred from the transcript analysis.",
    ),
    segment(
        D2_S2_LATE_AFTERNOON,
        "2026-03-04",
        "Stage 2 Late Afternoon Agentic SOC AI Incidents Vuln Discovery",
        6,
        "Unidentified Reversek / Spiky presenter",
        "Effort Is All You Need: Testing LLM Applications for Prompt Injection with Spiky",
        "01:03:15.556",
        "01:18:24.536",
        notes="The transcript names the tool and organization but not the speaker cleanly.",
        divergence="This extra lightning talk appears instead of one of the published late-afternoon talks.",
    ),
    segment(
        KEN_LUNCH,
        "2026-03-03",
        "Lunch Chat Ken Huang Agentic AI",
        1,
        "Ken Huang",
        "Lunch chat on agentic AI identity, governance, and deployment security",
        "00:02:43",
        "01:03:53",
        role="discussion",
        notes="Open discussion led by Ken Huang; brief unrelated carry-over lines at the very start are excluded.",
    ),
    segment(
        RICH_BOF,
        "2026-03-04",
        "Birds of a Feather Agentic Identity Architecture",
        1,
        "Rich Mogull",
        "Birds of a Feather: agentic identity architecture",
        "00:00:02",
        "00:30:28",
        role="discussion",
        notes="The file topic matches, but Rich Mogull is the clearly audible lead rather than Chris Cochran.",
        divergence="The recording title names Chris Cochran, but the transcript is led by Rich Mogull.",
    ),
]

UNMAPPED_FRAGMENTS = [
    unmapped(
        r"data\unpromptedcon-org\vtt\2026-03-02T213946Z__88638588165__dr-at-secwest.net__Webinar-session__audio_transcript__6df5fd5e-ea53-4ce8-9e1d-3a164d997529.vtt",
        "Tiny backstage/setup fragment",
        "Tammy Coxen says the room should have a lobby and should not be streaming. No actual webinar content is present.",
    ),
    unmapped(
        r"data\unpromptedcon-org\vtt\2026-03-04T004414Z__89437548757__dr-at-secwest.net__Happy-Hour-Manish-Gupta-Director-Expedia-Group-AI-Agent-Authentication-and-Autho__audio_transcript__f3739808-cc15-434e-8f5e-dbbc4ca407b8.vtt",
        "Tiny backstage/setup fragment",
        "Tammy Coxen and Manish Gupta discuss host permissions and turning off recording; no actual happy-hour discussion is captured.",
    ),
    unmapped(
        r"data\unpromptedcon-org\vtt\2026-03-04T005034Z__86340201112__dr-at-secwest.net__Happy-Hour-Silas-Cutler-Researcher-Censys-Self-Hosted-AI__audio_transcript__e0c8e0c0-1794-4ea3-846f-a1abe2276ff4.vtt",
        "Tiny backstage/setup fragment",
        "Dragos Ruiu discusses Zoom host handoff; Silas Cutler's actual discussion is not present.",
    ),
    unmapped(
        r"data\unpromptedcon-org\vtt\2026-03-04T195130Z__87957364582__dr-at-secwest.net__Lunch-Chat-Bruce-Schneier-Lecturer-Harvard-University-of-Toronto-AI-Integrity__audio_transcript__5f575c36-f62a-47d0-8567-b778343bba43.vtt",
        "Wrong-session fragment",
        "This file contains a short fragment from Brooks McMillin's stage talk rather than Bruce Schneier's lunch chat.",
    ),
    unmapped(
        r"data\unpromptedcon-org\vtt\2026-03-04T195224Z__89794507079__dr-at-secwest.net__Lunch-Chat-Dani-Z-IR-for-an-Airline-Secure-AI-Usage-in-Enterprise__audio_transcript__cccb8f64-c7c6-48df-89d0-009b2e0674bc.vtt",
        "Wrong-session fragment",
        "This file is a tiny continuation of the same Brooks McMillin stage-talk fragment, not Dani Z's lunch chat.",
    ),
    unmapped(
        r"data\unpromptedcon-org\vtt\2026-03-04T195242Z__85853094870__dr-at-secwest.net__Lunch-Chat-Marc-Rogers-CTO-nbhd.ai-open-discussion__audio_transcript__4d34ecb6-94d6-47d7-a1b8-5c49bd4168a4.vtt",
        "Wrong-session fragment",
        "This file is only a few seconds of the same stray Brooks McMillin stage-talk fragment.",
    ),
    unmapped(
        r"data\unpromptedcon-org\vtt\2026-03-04T195313Z__83121111824__dr-at-secwest.net__Lunch-Chat-Philippe-Langlois-CEO-P1-Security-Defense-and-Offense-of-Critical-Inf__audio_transcript__40efa128-2fdc-4ae9-bc39-c5466261f617.vtt",
        "Wrong-session fragment",
        "This file is an extremely short continuation of the same stray stage-talk fragment rather than Philippe Langlois's discussion.",
    ),
    unmapped(
        r"data\unpromptedcon-org\vtt\2026-03-04T235254Z__86365274778__dr-at-secwest.net__Happy-Hour-Elie-Bursztein-Research-Scientist-Google-open-discussion__audio_transcript__50dc0ec1-c376-4334-b9a0-67c184af5fe3.vtt",
        "Tiny backstage/setup fragment",
        "Only a brief Tammy Coxen setup line is present; Elie Bursztein's discussion is not captured.",
    ),
]


def main() -> int:
    METADATA_DIR.mkdir(parents=True, exist_ok=True)

    plan = {
        "description": "Presenter-level split plan for cleaned unpromptedcon Zoom transcripts.",
        "segments": SEGMENTS,
    }

    summary = {
        "segments": len(SEGMENTS),
        "unmapped_fragments": len(UNMAPPED_FRAGMENTS),
        "plan_path": str(METADATA_DIR / "presenter_split_plan.json"),
    }

    (METADATA_DIR / "presenter_split_plan.json").write_text(
        json.dumps(plan, indent=2, sort_keys=False),
        encoding="utf-8",
    )
    (METADATA_DIR / "unmapped_fragments.json").write_text(
        json.dumps(UNMAPPED_FRAGMENTS, indent=2, sort_keys=False),
        encoding="utf-8",
    )
    print(json.dumps(summary, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
